# Generated by Django 5.2.8 on 2025-11-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('umur', models.IntegerField()),
                ('alamat', models.TextField(blank=True)),
            ],
        ),
    ]
